### ISSUE TITLE
AnimationLoader missing InjectionToken LottieOptions

### ISSUE THREAD

**Issue by praveen-sivadasan** [ngx-lottie/ngx-lottie#151] opened 2022-11-16 15:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently using LottieModule.forRoot in angular applications is throwing an error with InjectionToken
```
global-error-handler.ts:16 NullInjectorError: R3InjectorError(DialerModule)[AnimationLoader -> AnimationLoader -> AnimationLoader -> InjectionToken LottieOptions -> InjectionToken LottieOptions -> InjectionToken LottieOptions]: 
  NullInjectorError: No provider for InjectionToken LottieOptions!

```
## Expected behavior

The animation shouldn't be broken when the existing configuration is used.

## Minimal reproduction of the problem with instructions

* Step 1 - Setup the library by following the usage section https://github.com/ngx-lottie/ngx-lottie#usage
* Step 2 - Import LottieModule into AppModule
* Step 3 - While using ng-lottie on components animation is broken and is not disaplyed

## What is the motivation / use case for changing the behavior?

Regression from https://github.com/ngx-lottie/ngx-lottie/pull/149/files#diff-19375bf16ff14c8eb4567903bc577358d927a82fd8a05ba33c45abb38b9cbb98

## Environment

<pre><code>
Libs:
- @angular/core version: 14.2.0
- ngx-lottie version: 9.1.0

Browser:
- [x] Chrome (desktop) version 107.0.5304.11
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v16.18.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by arturovt** [comment] 2022-11-16 15:36
Can you provide a _minimal reproducible example_?

**Comment by praveen-sivadasan** [comment] 2022-11-16 15:38
https://github.com/ngx-lottie/ngx-lottie/pull/152, another solution is to manually provide AnimationLoader along with LottieModule by consumers. But till that change is made by consumers the animation will be broken.

**Comment by praveen-sivadasan** [comment] 2022-11-16 15:58
I should have mentioned, the issue is happening when using micro-frontends. https://webpack.js.org/concepts/module-federation/

One of the micro-frontend(MFE) is injecting the module LottieModule. But when the MFE is used with the Shell the root is not of the MFE but the shell. Hence the root level AnimationLoader is not getting the injection token LOTTIE_OPTIONS which was provided in the MFE bootstrap module.

Is there a strong reason to not provide the AnimationLoader in LottieModule? When it comes to micro-frontends if AnimationLoader is not provided with the exported LottieModule then this can get tricky.

**Comment by praveen-sivadasan** [comment] 2022-11-16 16:29
Yes, make sense. But that shouldn't be at the expense of not supporting existing implementations. Most of the components we have are not standalone yet. So we will have to stick with a module-based approach. 
Can you discuss this with your team and let me know?

**Comment by cihancelen** [comment] 2022-11-21 13:29
Hello, unfortunately I am having the same problem :(

**Comment by arturovt** [comment] 2022-11-21 13:47
I’m just wondering what is the case because most of the Angular services are also marked as root providers right now (in the same way as animation loader). I’m familiar with micro frontends but not through the module federation. Is it possible to make a small example?

**Comment by 7elmon** [comment] 2022-11-22 13:43
> I’m just wondering what is the case because most of the Angular services are also marked as root providers right now (in the same way as animation loader). I’m familiar with micro frontends but not through the module federation. Is it possible to make a small example?

Hi! Just follow the instructions presented right here, under the title USAGE and before the title STANDALONE. You will see that angular will give an error message in the browser console and the project will not load (the error pointed out by Praveen).

Thanks!

**Comment by arturovt** [comment] 2022-11-22 13:53
Those instructions don’t help because the repo contains an integration app which uses the following approach.

**Comment by 7elmon** [comment] 2022-11-22 14:08
Well... if ngx-lottie doesn't support "non-standalone" components anymore, that's the problem.

**Comment by arturovt** [comment] 2022-11-22 17:36
Well, I'm a bit confused right now where this discussion turns off. The ngx-lottie supports both standalone and non-standalone approach. I asked you to provide a minimal reproducible example. I can't do more than guessing what's happening on your side because I don't see your code.

**Comment by 7elmon** [comment] 2022-11-23 01:12
I don't know what to tell you after asking you to just follow the official instructions. Ngx-lottie don't work with non-standalone components anymore. Praveen pointed out the details.

**Comment by arturovt** [comment] 2022-11-23 07:01
![image](https://user-images.githubusercontent.com/7337691/203488686-7b8b4907-a88a-4541-8105-aba77f33aec2.png)

**Comment by arturovt** [comment] 2022-11-23 07:03
Most open source policies of GitHub projects (as Angular, React, etc.) are that issues reported without a reproduction are closed immediately and then reopened once a reproduction has been provided. Since I asked you multiple times to provide an example and you just pointed me to the `#usage` section you guys show disrespect by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducable issues.

**Closed by arturovt** 2022-11-23 07:03 UTC

**Comment by Krab00** [comment] 2023-01-05 01:02
> Please, follow the official instructions and you'll see that ngx-lottie don't work with non-standalone components anymore. Praveen pointed out the details. Thanks!

For all people coming with the same issue. Pls remember to add the 
` provideLottieOptions({
      player: () => import(/* webpackChunkName: 'lottie-web' */ 'lottie-web'),
    }),
    `
in your **main.ts** file. Not in your standalone app.component.ts
