### ISSUE TITLE
Jest 27 compatibility issue

### ISSUE THREAD

**Issue by julien-von-oetinger** [ngx-lottie/ngx-lottie#108] opened 2021-06-17 08:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have updated Jest to version 27.0.4 and ngx-lottie to 7.0.1 but now I have an issue with my tests:

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:/repositories/greenmotion-frontend/node_modules/ngx-lottie/ngx-lottie.d.ts:4
    export * from './index';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 | import { NgModule } from '@angular/core';
      3 | import player from 'lottie-web';
    > 4 | import { LottieModule } from 'ngx-lottie';
        | ^
      5 |
      6 | import { AnimationComponent } from './animation.component';
      7 |

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/lib/animation/animation.module.ts:4:1)

**NOTE:** If I downgrade to ngx-lottie 6.4.0, it works well with Jest 27.

## Expected behavior

Same behavior than ngx-lottie 6.4.0

## Minimal reproduction of the problem with instructions

Update Jest to version 27.0.4 and ngx-lottie to 7.0.1

## What is the motivation / use case for changing the behavior?

I have update my project to Jest 27.

## Environment

<pre><code>
Libs:
- @angular/core version: 12.0.5
- ngx-lottie version: 7.0.1
- jest: 27.0.4

For Tooling issues:
- Node version: v16.1.0  
- Platform: Windows

**Comment by arturovt** [comment] 2021-06-27 15:32
Hey, thanks for the issue! Unfortunately, I don't have time trying to reproduce the issue locally and that would be great if you provide a minimal reproducible example, hence I can quickly look into it and find the issue. Thanks in advance!

**Comment by arturovt** [comment] 2021-07-05 15:59
Ok, the same issue has just appeared in another repository. This was caused by the Nx builder, I've changed the builder and published `ngx-lottie@7.0.2`, could you give it a try?

**Comment by arturovt** [comment] 2021-07-05 18:53
I'll close the issue since I've tried it inside the Nx workspace with Jest 27.

**Closed by arturovt** 2021-07-05 18:53 UTC
