### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by bl9l** [ngx-lottie/ngx-lottie#80] opened 2020-11-24 07:40 UTC
Hi.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I try to specify animation like this
```ts
  opts = {
    path: "https://ffom2.csb.app/assets/anim.json",
    loop: false,
    renderer: "svg"
  };
```
then it works just fine. But specifying animation like this 
```ts
opts = {
    animationData: animData, // imported JSON
    loop: false,
    renderer: "svg"
  };
```
it become wierd. The animation gets additional lines.

## Expected behavior
Exact same behaviour for specifying `path` or `animationData` in animation options.

## Minimal reproduction of the problem with instructions
You can see the bug [here](https://codesandbox.io/s/musing-microservice-ffom2?file=/src/app/app.component.ts). It has to have just pulsing cross at the middle of the animation. And it does on its first loop, but each next loop has more and more lines.
I know that the way how `animationData` property should work is by using `LottieTransferState.get('filename.json')`, but bug repeats with `LottieTransferState` either.

## Environment

<pre><code>
Libs:
- @angular/core version: 11.0.1
- ngx-lottie version: 6.4.0

Browser:
- [x] Chrome (desktop) version 86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 82
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.8.0
- Platform:  Windows

**Comment by arturovt** [comment] 2020-12-07 12:15
Hey, thanks for the issue. I was able to debug a little bit using your _codesandbox_.

I removed `ng-lottie` component and re-created this animation using `lottie-web` directly just to ensure where this issue is coming from:
```ts
import { Component, ElementRef, NgZone, ViewChild } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import * as animData from '../assets/anim.json';

const player = require('lottie-web');

@Component({
  selector: 'app-root',
  template: ` <div style="width: 200px; height: 200px;" #container></div> `,
})
export class AppComponent {
  opts = {
    loop: false,
    renderer: 'svg' as 'svg',
    // path: "https://ffom2.csb.app/assets/anim.json"
    // with LottieTransferState the same bug
    animationData: animData,
  };
  opts$ = new BehaviorSubject(this.opts);

  @ViewChild('container', { static: true }) container!: ElementRef<HTMLElement>;

  constructor(private ngZone: NgZone) {
    console.log(animData);

    // patching the handler according to
    // https://www.npmjs.com/package/ngx-lottie#listening-to-lottie-web-events
    const origRepeat = this.repeat.bind(this);
    this.repeat = () => this.ngZone.run(() => origRepeat());
  }

  ngOnInit() {
    this.opts$.subscribe((options) => {
      this.ngZone.runOutsideAngular(() => {
        const animationItem = player.loadAnimation({
          ...options,
          container: this.container.nativeElement,
        });

        animationItem.addEventListener('complete', () => {
          animationItem.destroy();
          this.repeat();
        });
      });
    });
  }

  repeat() {
    console.log(123);
    this.opts$.next({ ...this.opts });
  }
}
```

The problem remains the same when using the  `lottie-web` directly. This means that the problem is in the `lottie-web` package itself.

I will close this issue since the problem is not with the `ngx-lottie` package. I think you could transfer your issue to `lottie-web` repository and provide more simpler reproducible example for them (w/o using Angular).

Feel free to re-open if I'm missing anything.

**Closed by arturovt** 2020-12-07 12:15 UTC
