### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by riazXrazor** [ngx-lottie/ngx-lottie#54] opened 2020-05-17 13:44 UTC
## Possible memory leak

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

page becomes unresponsive after few route changes

## Expected behavior

page should be responsive

## Minimal reproduction of the problem with instructions
just changing routes
 - https://inadev-redesign-dev.oitsystems.com/#/?viewId=customers
 - https://inadev-redesign-dev.oitsystems.com/#/?viewId=credentials_card
 - https://inadev-redesign-dev.oitsystems.com/#/contracts/contract
 - https://inadev-redesign-dev.oitsystems.com/#/wearehiring/hiring

## What is the motivation / use case for changing the behavior?

N/A

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- ngx-lottie version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.3
- Platform:   Windows

Others:

</code></pre>
![s1](https://user-images.githubusercontent.com/13194363/82148137-2142b380-9870-11ea-856c-297cc390019c.PNG)
![s2](https://user-images.githubusercontent.com/13194363/82148135-20aa1d00-9870-11ea-91c9-875b88aab5af.PNG)
![s3](https://user-images.githubusercontent.com/13194363/82148133-1f78f000-9870-11ea-8759-ed82f39256ad.PNG)

![ezgif-6-e042fbd808d5](https://user-images.githubusercontent.com/13194363/82151879-789a5100-987b-11ea-9371-ed895e557bea.gif)

**Comment by riazXrazor** [comment] 2020-05-17 13:48
```
 <ng-lottie
    [containerClass]="containerClass"
    [options]="options"
    loop= "true"
    autoplay= "true"
    (destroy) = "destroy($event)"
  ></ng-lottie>

destroy(animationItem: AnimationItem){
    animationItem = null;
  }
```
and setting `useCache` to `false` seems to fix it. 
```
LottieModule.forRoot({
      player: playerFactory,
      useCache: false,
    })
```

**Comment by arturovt** [comment] 2020-06-20 18:57
Hey. I'm sorry I was stuck at work and my hands have reached to that issue :)

This issue exists and the problem is not `useCache`. What `useCache` does is gets `animationData` from your animation when it gets loaded. The `animationData` is an object, it doesn't have any closures, `this` references or anything else. So the `useCache` is not a problem here.

I have probably found the root cause. I was testing it in this repository `integration` example. Then problem is the `shareReplay(1)` operator which is used to cache the `player` when it's loaded via dynamic import.

I've made some screenshots for that case:

![image](https://user-images.githubusercontent.com/7337691/85209427-8e9aa600-b340-11ea-94c4-bf57cff1dc9d.png)

The animation is destroyed actually. `destroy` is called with `LottieComponent.ngOnDestroy` that should've completed the subscriber, but it didn't. The snapshot above actually says that there is a memory leak since it shows the `Distance 24` which is a path from GC root.

When I replaced `shareReplay(1)` with `publishReplay(1), refCount()`:

![image](https://user-images.githubusercontent.com/7337691/85209453-dd484000-b340-11ea-8fe9-6a255cb48da1.png)

There is no distance and reference to `LottieComponent` instance, it can be garbage collected safely.

And when I also set `useCache: true`:

![image](https://user-images.githubusercontent.com/7337691/85209468-f6e98780-b340-11ea-8bf2-5237adfb9a11.png)

There is no distance too.

**Comment by arturovt** [comment] 2020-06-20 19:04
Also, unfortunately, I cannot say if there is a memory leak in your specific case. When you see an `AnimationItem` in the heap snapshot it doesn't mean that it's a memory leak. You'd better take a screenshot with the whole information (that is on the right pane). This is how generational garbage collector works.

**Comment by arturovt** [comment] 2020-06-20 19:17
I've published `ngx-lottie@6.1.1`.

**Comment by riazXrazor** [comment] 2020-06-20 19:22
tnx @arturovt will check it out.

**Comment by arturovt** [comment] 2020-06-20 19:28
Because this is what I see in my browser:

![image](https://user-images.githubusercontent.com/7337691/85210010-416d0300-b345-11ea-960d-c0648909e14f.png)

The `AnimationItem` persists in GC tree, but there is no distance from GC root to it, it means that the garbage collector will decide when to release it without asking anyone about _when_ :smile:

**Comment by arturovt** [comment] 2020-07-04 14:00
I will close this one since I debugged it multiple times and haven't found memory leaks (as I showed you my screenshots above). If you've got any questions feel free to open another issue, I'll be glad to help 😉

**Closed by arturovt** 2020-07-04 14:00 UTC
