### ISSUE TITLE
Error : No provider for InjectionToken LottieOptions!

### ISSUE THREAD

**Issue by 0xMemoryGrinder** [ngx-lottie/ngx-lottie#160] opened 2023-03-02 16:48 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I created an angular library to aggregate common logic of several products I maintain at work. The components I extracted to the library use ngx-lottie so I added <code>LottieModule.forRoot(options..)</code>  in my modules in my library.

Then i tested my library with a dead simple application with just an app module/component. This worked like a charm even if I needed to add LottieModule.forRoot in the AppModule.

Now I really start to create an application using my library and as soon as I added the angular router, I got an error in the console.
<pre><code>
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AuthenticationModule)[AnimationLoader -> AnimationLoader -> InjectionToken LottieOptions -> InjectionToken LottieOptions -> InjectionToken LottieOptions]: 
  NullInjectorError: No provider for InjectionToken LottieOptions!
NullInjectorError: R3InjectorError(AuthenticationModule)[AnimationLoader -> AnimationLoader -> InjectionToken LottieOptions -> InjectionToken LottieOptions -> InjectionToken LottieOptions]: 
  NullInjectorError: No provider for InjectionToken LottieOptions!
</code></pre>

(Check the file architecture schema below)
It only works as expected if I include my library modules directly in the AppModule AND in the AuthenticationModule (in the application)

## Expected behavior
I should be able to use ngx-lottie inside my library without having to import it in my application's modules

## Minimal reproduction of the problem with instructions

I cannot share the code as it the property of my company but here is my current file architecture:
<pre><code>
.
├── angular.json
├── package.json
├── package-lock.json
├── projects
│   └── zaion-ngx-product-frontend-common
│       ├── authentication
│       │   ├── core
│       │   │   ├── index.ts
│       │   │   ├── ng-package.json
│       │   │   ├── public-api.ts
│       │   │   └── src
│       │   │       ├── authenticated-user.service.ts
│       │   │       ├── authentication.module.ts (ignore this file, he is not relevant and do not confuse its name with the one in the application folder)
│       │   │       ├── authentication.service.spec.ts
│       │   │       ├── default-authenticated-user.service.ts
│       │   │       └── default-user.ts
│       │   ├── index.ts
│       │   ├── ng-package.json
│       │   ├── package.json
│       │   ├── package-lock.json
│       │   ├── public-api.ts
│       │   ├── README.md
│       │   ├── sign-in
│       │   │   ├── index.ts
│       │   │   ├── ng-package.json
│       │   │   ├── public-api.ts
│       │   │   ├── README.md
│       │   │   └── src
│       │   │       ├── components
│       │   │       │   ├── sign-in.component.html (this component uses the ngx-lottie component)
│       │   │       │   └── sign-in.component.ts
│       │   │       ├── config.token.ts
│       │   │       ├── services
│       │   │       │   ├── sign-in.service.spec.ts
│       │   │       │   └── sign-in.service.ts
│       │   │       ├── sign-in.config.ts
│       │   │       ├── sign-in.module.ts (this module import LottieModule.forRoot(...))
│       │   │       └── utils
│       │   │           └── custom-validators.utils.ts
│       │   ├── src
│       │   ├── tsconfig.lib.json
│       │   ├── tsconfig.lib.prod.json
│       │   ├── tsconfig.spec.json
│       │   └── two-factor
│       │       ├── index.ts
│       │       ├── ng-package.json
│       │       ├── public-api.ts
│       │       └── src
│       │           ├── config.token.ts
│       │           ├── two-factor.component.html (this component uses the ngx-lottie component)
│       │           ├── two-factor.component.ts
│       │           ├── two-factor.config.ts
│       │           ├── two-factor.module.ts (this module import LottieModule.forRoot(...))
│       │           └── two-factor.service.ts
│       └── README.md
├── README.md
├── src
│   ├── app
│   │   ├── app.component.html
│   │   ├── app.component.scss
│   │   ├── app.component.spec.ts
│   │   ├── app.component.ts
│   │   ├── app.module.ts (Should I import Lottie here even if my app does not uses it ?)
│   │   ├── app-routing.module.ts (define one route which loads AuthenticationModule)
│   │   └── authentication
│   │       ├── authentication.module.ts (import SignInModule and TwoFactorModule from the library
│   │       ├── authentication.routing.ts (define two routes for each component below)
│   │       ├── sign-in
│   │       │   ├── login.component.html (simple wrapper of the SignInComponent from the library)
│   │       │   └── login.component.ts
│   │       └── two-factor
│   │           ├── twoFA.component.html (simple wrapper of the TwoFactorComponent from the library)
│   │           └── twoFA.component.ts
│   ├── environments
│   │   ├── environment.prod.ts
│   │   ├── environment.ts
│   │   └── environment.type.ts
│   ├── favicon.ico
│   ├── index.html
│   ├── main.ts
│   └── styles.scss
├── tsconfig.app.json
├── tsconfig.json
└── tsconfig.spec.json

</code></pre>

## What is the motivation / use case for changing the behavior?
The package does not work correctly when used in a generic angular library.

## Environment

<pre><code>
Libs:
- @angular/core version: 15.2.0
- ngx-lottie version: 10.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Brave (Chromium) (desktop)
 
For Tooling issues:
- Node version: 18.12.1
- Platform:  Linux
</code></pre>

**Comment by csutorasr** [comment] 2023-07-17 14:48
Any update on this. I'm having the same problem since I updated it to Angular 16. The cause of this can be that the `AnimationLoader` is provided in `'root'` and the options are provided upper in the provider tree.

It would be nice to add a `provideAnimationLoader` function.

**Comment by csutorasr** [comment] 2023-07-17 15:03
As a workaround these can be provided in the component:

```typescript
@Component({
  providers: [
    provideLottieOptions({
      player: () => import(/* webpackChunkName: 'lottie-web' */ 'lottie-web'),
    }),
    AnimationLoader,
  ],
})
export class AComponent {}
```

**Comment by hardcorelite** [comment] 2023-09-20 12:43
Add to app.module.ts
`import player from 'lottie-web';
export function playerFactory() {
    return player;
}`
then
`imports: [
        LottieModule.forRoot({player: playerFactory})
       ...
`

**Comment by arturovt** [comment] 2023-09-20 13:08
I'm closing the issue for now because there's no reproducible example provided in here. This is required to ensure effective troubleshooting.

I'm able to troubleshoot and fix the issue (if necessary) if I reproduce it locally. That's not possible to pinpoint the issue without a minimal reproducible example.

Feel free to re-open this issue once you have a running example.

**Closed by arturovt** 2023-09-20 13:08 UTC

**Comment by InocentumAbhijit** [comment] 2023-09-22 20:53
> As a workaround these can be provided in the component:
> 
> ```ts
> @Component({
>   providers: [
>     provideLottieOptions({
>       player: () => import(/* webpackChunkName: 'lottie-web' */ 'lottie-web'),
>     }),
>     AnimationLoader,
>   ],
> })
> export class AComponent {}
> ```

Only adding `AnimationLoader` worked for me :-)
Thanks 👍

**Comment by KerimM** [comment] 2023-11-04 14:41
> > As a workaround these can be provided in the component:
> > ```ts
> > @Component({
> >   providers: [
> >     provideLottieOptions({
> >       player: () => import(/* webpackChunkName: 'lottie-web' */ 'lottie-web'),
> >     }),
> >     AnimationLoader,
> >   ],
> > })
> > export class AComponent {}
> > ```
> 
> Only adding `AnimationLoader` worked for me :-) Thanks 👍

I had the same problem in an ionic project based on angular 14 and adding only AnimationLoader worked

**Comment by OverPa1n** [comment] 2024-04-15 12:54
> > As a workaround these can be provided in the component:
> > ```ts
> > @Component({
> >   providers: [
> >     provideLottieOptions({
> >       player: () => import(/* webpackChunkName: 'lottie-web' */ 'lottie-web'),
> >     }),
> >     AnimationLoader,
> >   ],
> > })
> > export class AComponent {}
> > ```
> 
> Only adding `AnimationLoader` worked for me :-) Thanks 👍

Work for me

**Comment by HiddenWally** [comment] 2024-04-19 18:59
In Angular 17, I encountered a similar issue and the solution was to add the following to the AppModule:

```typescript
providers: [
    provideLottieOptions({
      player: () => import('lottie-web'),
    }),
  ],
```
