### ISSUE TITLE
How used Lottie interactivity 

### ISSUE THREAD

**Issue by monsieurPaon** [ngx-lottie/ngx-lottie#87] opened 2021-02-26 16:50 UTC
Hi team, 

How we can used the lottie interactivity features with ngx-lottie ? 
https://lottiefiles.com/interactivity 

Ia have try to install the lib https://github.com/LottieFiles/lottie-interactivity but i can't find a method to manipulate the ng-lottie... (Notice i'm new in the lottie game :D ) 

Regards, 

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

**Comment by arturovt** [comment] 2021-02-26 18:15
Hey @monsieurPaon Thanks for the issue.

Unfortunately, I'm unaware of what is that interactivity feature. Could you elaborate more on that?

**Comment by monsieurPaon** [comment] 2021-02-26 18:30
Thank you for the quick reply! 

I speak about this => https://lottiefiles.com/interactivity 

With this the animation can follow the speed of you scroll. 

Exemple of code: 

`<script>
LottieInteractivity.create({
  mode:"scroll",
  player: "#thirdLottie" 
  actions: [
    {
      visibility: [0, 0.3],
      type: "stop",
      frames: [0]
    },
    {
      visibility: [0.3, 1]
      type: "seek",
      frames: [0, 301]
    }
  ]
});
</script>`

**Comment by monsieurPaon** [comment] 2021-04-07 14:53
Hi @arturovt , any news regarding this ?

**Comment by arturovt** [comment] 2021-04-07 15:50
Hey, I'm not sure how this library is related to `lottie-web`. I see that it works with the `lottie-player` component (and also uses properties of this component) which is actually completely independent library that's not related to Angular.

**Comment by arturovt** [comment] 2021-04-16 12:27
Hey, I will close this issue due to the objective reason. I checked this package previously.

As I mentioned the `@lottiefiles/lottie-interactivity` package is compatible only with `@lottiefiles/lottie-player` (https://github.com/LottieFiles/lottie-player), it's a framework agnostic web component.

You can see that there is a `player` property which is passed to options when creating `LottieInteractivity`, the `player` property is a `lottie-player` DOM element which is also a web component with custom methods. It's then used by `LottieInteractivity`, you can check here:

https://github.com/LottieFiles/lottie-interactivity/blob/master/src/main.js#L142-L146

**Closed by arturovt** 2021-04-16 12:27 UTC

**Comment by me-dira** [comment] 2021-12-12 06:54
> > Hey, I will close this issue due to the objective reason. I checked this package previously.
> > As I mentioned the `@lottiefiles/lottie-interactivity` package is compatible only with `@lottiefiles/lottie-player` (https://github.com/LottieFiles/lottie-player), it's a framework agnostic web component.
> > You can see that there is a `player` property which is passed to options when creating `LottieInteractivity`, the `player` property is a `lottie-player` DOM element which is also a web component with custom methods. It's then used by `LottieInteractivity`, you can check here:
> > https://github.com/LottieFiles/lottie-interactivity/blob/master/src/main.js#L142-L146
> 
> So if we use ngx-lottie we can't use interactivity? Or at least playsegments thats what I need (animationItem.playsegments wont work, neither .pause etc)
> 
> EDIT:
> 
> nvm animationItem.pause(); etc works BUT if I wrap it inside a timeOut function (don't know why tho...)

It's because animation is loading as asynchronize and you it takes time to load. Please use events that are implemented to do your task.
for example: If you want to do something with animation when its created then you have to use `animationCreated` event.

At first your animation is null or undefined because it takes time for lottie-web to render it but after that angular updates the data when its ready and its the cause of your problem.
